### ISSUE TITLE
Cant Compile Commit 3244

### ISSUE THREAD

**Issue by roswitina** [pjrinaldi/wombatforensics#313]
**Describe the bug**
Cant compile commit 3244.

**To Reproduce**
1. git clone .....
2. ./archinstall.sh or later make
3. See compile error 

.....
wombatfunctions.cpp:8:10: schwerwiegender Fehler: scalpel.h Datei oder Verzeichnis nicht gefunden
     8 | #include <scalpel.h>
Kompilierung beendet
...........

**Comment by pjrinaldi** [comment]
I apologize for the issue you ran into. It appears you are running the ./archinstall.sh script against the "master" branch, but it needs to be run against the "v0.2" branch.

The master branch currently doesn't really work as I am working on implementing new features and have only just started on them...

I will switch tactics and go from a git clone, then run ./archinstall.sh to a download archinstall and run, and it will get the right v0.2 branch. I will close this once that has been implemented...

**Comment by pjrinaldi** [comment]
Here are the updated instructions to ensure you are using the v0.2 branch release:

1. Download the v0.2 assets from the releases page: [wombat forensics v0.2 tar.gz](https://github.com/pjrinaldi/wombatforensics/archive/v0.2.tar.gz)
2. tar -xzf the downloaded file.
3. run the archinstall.sh script.

Again, sorry for the issues and thanks for your interest. I just ran a test using this method and it worked. Let me know if you have any other issues. I'm gonna close the ticket, but feel free to reopen or submit a new ticket if you run into any other issues.
